#!/usr/bin/env bash

paru -S --noconfirm --needed \
	just \
	gimp \
	tldr \
	go \
	btop \
	bc \
	bun \
	nodejs \
	npm \
	love \
	ghostty \
	wlogout-git \
	ffmpeg \
	aalib \
	ascii-image-converter-bin

curl -sSfL https://get.tur.so/install.sh | bash
