##############################
### WINDOWS AND WORKSPACES ###
##############################

# WINDOWS
windowrule = match:class firefox, workspace 2

windowrule = match:class kitty, workspace 3

windowrule = match:class Slack, workspace 5

# WORKSPACES
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
